mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: MYBATISDEV
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
crossOrigin: http://localhost:8080
